name: AGMoney
main: me.libraryaddict.Currency.CurrencyMain
version: 1.2.3
commands:
  bal:
    aliases: [balance]
  pay:
    description: Pay a player
  money:
    description: Description
  moneylog:
    description: Description
  setbal:
    description: Set a players balance
    usage: /<command> <player> <balance>